# FEDE Embedding Fine-Tuning Pipeline

Run each stage in order. Each cell is independent — you can re-run any stage without repeating earlier ones.

| Stage | What it does |
|---|---|
| 0 | Sanity checks |
| 1a | Generate queries (LLM only, no embedding model) |
| 1b | Assemble training pairs (embedding + positive assignment) |
| 2 | Generate eval queries |
| 3 | Train Round 1 |
| 4 | Mine hard negatives |
| 5 | Train Round 2 |
| 6 | Evaluate |
| 7 | Index corpus into Qdrant |

## Configuration

Edit these before running anything.

In [2]:
# ── How many movies to use for training (rest become eval pool) ──────────────
TRAIN_MOVIES     = 1200
N_EVAL_QUERIES   = 100       # held-out eval queries to generate

# ── Output directories ───────────────────────────────────────────────────────
ROUND1_MODEL_DIR = "fede-embeddinggemma/round1"
ROUND2_MODEL_DIR = "fede-embeddinggemma/round2"

# ── Training overrides (None = use config.py defaults) ───────────────────────
EPOCHS      = None   # e.g. 1 for a quick test
BATCH_SIZE  = 8      # per-device batch; try 2 on 8–12GB if you OOM
LR          = None   # e.g. 1e-5
USE_LORA    = True   # False = full fine-tune (needs more VRAM)
CACHED_MNRL_MINI_BATCH = 8   # CachedMNRL sub-batch; lower if OOM (e.g. 4)

# ── Evaluation ───────────────────────────────────────────────────────────────
EVAL_MOVIES = None   # None = full 1338-movie corpus; set e.g. 500 to save RAM

---
## Stage 0 — Sanity checks

Verify environment, credentials, and data before committing hours of compute.

In [3]:
import logging, os, json
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("pipeline")

# ── Project root ─────────────────────────────────────────────────────────────
import finetuning.config as cfg
log.info("Project root: %s", cfg.PROJECT_ROOT)

# ── Tagged scripts ────────────────────────────────────────────────────────────
tagged_files = list(cfg.TAGGED_SCRIPTS_DIR.glob("*.txt"))
log.info("Tagged scripts found: %d", len(tagged_files))
assert len(tagged_files) > 0, f"No tagged scripts in {cfg.TAGGED_SCRIPTS_DIR}"

# ── Metadata ─────────────────────────────────────────────────────────────────
with open(cfg.METADATA_PATH) as f:
    meta = json.load(f)
log.info("Metadata entries: %d", len(meta))

# ── Gemini API key (used by Batch API for dataset generation) ─────────────────
gemini_key = os.getenv("GEMINI_API_KEY", "")
assert gemini_key, "GEMINI_API_KEY is not set in .env"
log.info("Gemini key: %s…%s", gemini_key[:8], gemini_key[-4:])

# ── HF token (for gated embedding model) ─────────────────────────────────────
hf_token = os.getenv("HF_TOKEN", "")
if hf_token:
    log.info("HF_TOKEN present")
else:
    log.warning("HF_TOKEN not set — fine unless you switched to a gated model")

# ── Existing data ─────────────────────────────────────────────────────────────
raw_path  = cfg.FINETUNING_DATA_DIR / "raw_queries.jsonl"
r1_path   = cfg.FINETUNING_DATA_DIR / "training_pairs_r1.jsonl"
r2_path   = cfg.FINETUNING_DATA_DIR / "training_pairs_r2.jsonl"
eval_path = cfg.FINETUNING_DATA_DIR / "eval_queries.json"
ckpt_path = cfg.FINETUNING_DATA_DIR / "querygen_checkpoint.json"

def _count(p): return sum(1 for _ in open(p)) if p.exists() else 0

print(f"\nCurrent data state:")
print(f"  raw_queries.jsonl       : {_count(raw_path):>6} lines")
print(f"  training_pairs_r1.jsonl : {_count(r1_path):>6} lines")
print(f"  training_pairs_r2.jsonl : {_count(r2_path):>6} lines")
print(f"  eval_queries.json       : {'exists' if eval_path.exists() else 'missing'}")
print(f"  querygen_checkpoint.json: {'exists' if ckpt_path.exists() else 'missing'}")
if ckpt_path.exists():
    ckpt = json.loads(ckpt_path.read_text())
    print(f"    → {len(ckpt.get('processed_movies', []))} movies in checkpoint, status={ckpt.get('status', 'in_progress')}")

print("\n✅ Sanity checks passed")

2026-03-24 07:35:16,826 [INFO] Project root: C:\Users\anzez\University\ML\fede
2026-03-24 07:35:16,830 [INFO] Tagged scripts found: 1338
2026-03-24 07:35:16,848 [INFO] Metadata entries: 1384
2026-03-24 07:35:16,849 [INFO] Gemini key: AIzaSyC1…QQDE
2026-03-24 07:35:16,850 [INFO] HF_TOKEN present

Current data state:
  raw_queries.jsonl       :   6946 lines
  training_pairs_r1.jsonl :   5892 lines
  training_pairs_r2.jsonl :   5892 lines
  eval_queries.json       : exists
  querygen_checkpoint.json: exists
    → 1200 movies in checkpoint, status=queries_complete

✅ Sanity checks passed

---
## Stage 1a — Generate queries (LLM only)

Calls the LLM for every movie to produce Type A (synopsis) and Type B (scene summary) queries.
No embedding model is loaded during this stage — only API calls.

- Checkpoints every 50 movies. Safe to interrupt and resume.
- Output: `data/finetuning/raw_queries.jsonl`
- Uses structured output (Pydantic schemas) to guarantee valid JSON from the LLM.

In [ ]:
# ── Stage 1a: Generate queries via LLM (no embedding model) ─────────────────
from finetuning.dataset.dataset_builder import DatasetBuilder

builder = DatasetBuilder(max_movies=TRAIN_MOVIES)
raw_queries_path = builder.generate_queries(resume=True)

n_queries = sum(1 for _ in open(raw_queries_path))
print(f"\n✅ Stage 1a complete: {n_queries} raw queries → {raw_queries_path}")
print("You can now safely restart the kernel before running Stage 1b.")

In [3]:
import gc

# Free QueryGenerator / LLM client before loading the embedding model.
if "builder" in dir():
    del builder
gc.collect()
print("Stage 1a objects released")

Stage 1a objects released

In [4]:
# ── Stage 1b: Assemble training pairs (embedding + positive assignment) ──────
# Reads raw_queries.jsonl, loads embedding model, finds best positive scene
# per query, samples random negatives, and writes training_pairs_r1.jsonl.
#
# No LLM API calls — purely local compute.
# Safe to interrupt and resume — already-processed movies are skipped.

from finetuning.dataset.dataset_builder import DatasetBuilder

builder = DatasetBuilder(max_movies=TRAIN_MOVIES)
r1_path = builder.assemble_pairs(resume=True)

pairs = sum(1 for _ in open(r1_path))
print(f"\n✅ Stage 1b complete: {pairs} training pairs → {r1_path}")

2026-03-23 22:19:12,904 [INFO] Scene corpus built: 1200 movies, 117100 total scenes
2026-03-23 22:19:12,905 [INFO] Loading embedding model google/embeddinggemma-300m on cuda …
2026-03-23 22:19:12,906 [INFO] Loading embedding model: google/embeddinggemma-300m
2026-03-23 22:19:12,908 [INFO] Load pretrained SentenceTransformer: google/embeddinggemma-300m
2026-03-23 22:19:13,047 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-23 22:19:13,175 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-23 22:19:13,306 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-23 22:19:13,422 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/README.md "HTTP/1.1 200 OK"
2026-03-23 22:19:13,547 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-23 22:19:13,670 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-03-23 22:19:13,811 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-03-23 22:19:13,936 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 22:19:14,062 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3417.84it/s]
2026-03-23 22:19:14,533 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 22:19:14,665 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-23 22:19:14,801 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-23 22:19:14,920 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-23 22:19:17,395 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-23 22:19:17,522 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/1_Pooling/config.json "HTTP/1.1 200 OK"
2026-03-23 22:19:17,646 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/config.json "HTTP/1.1 200 OK"
2026-03-23 22:19:17,780 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-23 22:19:17,913 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/config.json "HTTP/1.1 200 OK"
2026-03-23 22:19:18,080 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-23 22:19:18,206 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-23 22:19:18,289 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-23 22:19:18,290 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-23 22:19:18,310 [INFO] Assembling pairs: 5892 queries across 1199 movies (0 already done)
2026-03-23 22:19:45,709 [INFO]   [50/1199] 248 pairs written so far …
2026-03-23 22:20:15,502 [INFO]   [100/1199] 504 pairs written so far …
2026-03-23 22:20:47,293 [INFO]   [150/1199] 776 pairs written so far …
2026-03-23 22:21:18,686 [INFO]   [200/1199] 1039 pairs written so far …
2026-03-23 22:21:47,807 [INFO]   [250/1199] 1297 pairs written so far …
2026-03-23 22:22:13,477 [INFO]   [300/1199] 1530 pairs written so far …
2026-03-23 22:22:43,607 [INFO]   [350/1199] 1782 pairs written so far …
2026-03-23 22:23:11,183 [INFO]   [400/1199] 2026 pairs written so far …
2026-03-23 22:23:43,983 [INFO]   [450/1199] 2293 pairs written so far …
2026-03-23 22:24:13,630 [INFO]   [500/1199] 2549 pairs written so far …
2026-03-23 22:24:42,645 [INFO]   [550/1199] 2806 pairs written so far …
2026-03-23 22:25:09,797 [INFO]   [600/1199] 3063 pairs written so far …
2026-03-23 22:25:39,167 [INFO]   [650/1199] 3313 pairs written so far …
2026-03-23 22:26:08,292 [INFO]   [700/1199] 3569 pairs written so far …
2026-03-23 22:26:38,510 [INFO]   [750/1199] 3828 pairs written so far …
2026-03-23 22:27:10,266 [INFO]   [800/1199] 4078 pairs written so far …
2026-03-23 22:27:41,418 [INFO]   [850/1199] 4331 pairs written so far …
2026-03-23 22:28:10,848 [INFO]   [900/1199] 4559 pairs written so far …
2026-03-23 22:28:41,760 [INFO]   [950/1199] 4808 pairs written so far …
2026-03-23 22:29:25,608 [INFO]   [1000/1199] 5065 pairs written so far …
2026-03-23 22:29:54,591 [INFO]   [1050/1199] 5288 pairs written so far …
2026-03-23 22:30:29,876 [INFO]   [1100/1199] 5543 pairs written so far …
2026-03-23 22:31:01,325 [INFO]   [1150/1199] 5791 pairs written so far …
2026-03-23 22:31:04,336 [INFO] Stage 2 complete: 5892 training pairs → C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r1.jsonl

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\anzez\\University\\ML\\fede\\data\\finetuning\\querygen_checkpoint.tmp' -> 'C:\\Users\\anzez\\University\\ML\\fede\\data\\finetuning\\querygen_checkpoint.json'

In [5]:
import gc

# Free embedding model + corpus from Stage 1b before loading training model.
if "builder" in dir():
    del builder
gc.collect()
print("Stage 1b objects released")

Stage 1b objects released

In [ ]:
# (Optional) Clear the checkpoint to force a full re-run of Stage 1a
# import os
# ckpt = cfg.FINETUNING_DATA_DIR / "querygen_checkpoint.json"
# if ckpt.exists():
#     os.remove(ckpt)
#     print("Checkpoint cleared")

In [ ]:
# (Legacy) Run both stages in one call — use Stage 1a + 1b cells above instead.
# from finetuning.dataset.dataset_builder import DatasetBuilder
# builder = DatasetBuilder(max_movies=TRAIN_MOVIES)
# r1_path = builder.build(resume=True)
# pairs = sum(1 for _ in open(r1_path))
# print(f"\n✅ Stage 1 complete: {pairs} pairs → {r1_path}")

---
## Stage 2 — Generate eval queries

Generates ~100 held-out evaluation queries from movies **not** in the training set.

⚠️ Must run **after Stage 1** — reads the checkpoint to know which movies to exclude.

In [7]:
from finetuning.corpus.scene_corpus import load_metadata
from finetuning.dataset.query_generator import load_checkpoint
from finetuning.evaluation.dataset_generator import generate_eval_dataset

ckpt = load_checkpoint()
assert ckpt, "No checkpoint found — run Stage 1 first"
training_ids = set(ckpt.get("processed_movies", []))
log.info("Excluding %d training movies from eval pool", len(training_ids))

metadata = load_metadata()
eval_path = generate_eval_dataset(
    corpus_movie_ids=training_ids,
    metadata=metadata,
    n=N_EVAL_QUERIES,
)

with open(eval_path) as f:
    eval_queries = json.load(f)
print(f"\n✅ Stage 2 complete: {len(eval_queries)} eval queries → {eval_path}")
print("Sample:", eval_queries[0])

2026-03-22 21:25:19,391 [INFO] Excluding 1200 training movies from eval pool
2026-03-22 21:25:19,666 [INFO] Generating eval queries from 173 candidate movies (target: 100)
2026-03-22 21:25:24,962 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:27,826 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:31,396 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:36,323 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:38,631 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:42,140 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:47,436 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:49,436 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:52,052 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:56,678 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:59,831 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:03,971 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:06,822 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:10,341 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:13,964 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:16,571 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:19,706 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:23,460 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:27,230 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:30,849 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:33,586 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:38,023 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:40,607 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:46,041 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:48,530 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:51,483 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:53,471 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:55,844 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:57,850 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:01,750 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:05,732 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:08,803 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:12,020 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:15,176 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:18,518 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:21,461 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:24,366 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:28,058 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:31,234 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:36,252 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:39,609 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:44,400 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:47,472 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:50,372 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:54,573 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:59,578 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:01,094 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:05,413 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:08,072 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:10,219 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:13,679 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:17,084 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:20,397 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:23,893 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:25,655 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:28,950 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:31,857 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:35,179 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:38,751 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:41,949 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:46,924 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:50,668 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:53,807 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:57,370 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:02,541 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:04,576 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:09,454 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:14,280 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:19,414 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:24,481 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:27,997 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:31,515 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:34,381 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:36,807 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:40,047 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:43,476 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:46,617 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:49,617 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:52,169 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:55,727 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:58,710 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:03,361 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:08,361 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:13,473 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:16,629 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:18,606 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:22,383 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:27,667 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:30,184 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:35,175 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:37,866 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:40,223 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:45,286 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:48,224 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:51,842 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:57,480 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:01,465 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:04,276 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:07,441 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:08,991 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:12,138 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:14,016 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:14,100 [INFO] Eval dataset saved: 100 queries → C:\Users\anzez\University\ML\fede\data\finetuning\eval_queries.json

✅ Stage 2 complete: 100 eval queries → C:\Users\anzez\University\ML\fede\data\finetuning\eval_queries.json
Sample: {'query': 'A district attorney leads an extensive investigation into the assassination of a national president.', 'movie_id': 'jfk', 'movie_title': 'JFK'}

In [ ]:
# (Cleanup already handled by cells above)

---
## Stage 3 — Train Round 1

Fine-tunes the base embedding model on the round-1 dataset using `CachedMultipleNegativesRankingLoss`.
Runs retrieval eval (MRR / Accuracy@k) after each epoch if `eval_queries.json` exists.

💡 **VRAM:** Use small `BATCH_SIZE` (2–4), `USE_LORA = True`, and low `CACHED_MNRL_MINI_BATCH` (4–8) on 8–12GB GPUs. Optionally set `PYTORCH_ALLOC_CONF=expandable_segments:True` before starting Jupyter.

In [6]:
from finetuning.training.model import load_model
from finetuning.training.trainer import build_evaluator, build_trainer, load_training_dataset
from finetuning.corpus.scene_corpus import build_scene_corpus

model      = load_model()  # base model from config
train_data = load_training_dataset(r1_path)
log.info("Training samples: %d", len(train_data))

evaluator = None
if eval_path.exists():
    log.info("Building eval corpus for per-epoch evaluation …")
    eval_corpus = build_scene_corpus(max_movies=EVAL_MOVIES)
    evaluator = build_evaluator(eval_path, eval_corpus)
else:
    log.warning("eval_queries.json not found — training without per-epoch eval")

train_kwargs = {}
if EPOCHS     is not None: train_kwargs["num_epochs"]    = EPOCHS
if BATCH_SIZE is not None: train_kwargs["batch_size"]    = BATCH_SIZE
if LR         is not None: train_kwargs["learning_rate"] = LR

trainer = build_trainer(
    model=model,
    train_dataset=train_data,
    output_dir=ROUND1_MODEL_DIR,
    evaluator=evaluator,
    use_lora=USE_LORA,
    cached_mnrl_mini_batch=CACHED_MNRL_MINI_BATCH,
    **train_kwargs,
)

trainer.train()
model.save(ROUND1_MODEL_DIR)
print(f"\n✅ Stage 3 complete: round-1 model saved to {ROUND1_MODEL_DIR}")

2026-03-23 22:39:56,193 [INFO] Loading embedding model: google/embeddinggemma-300m
2026-03-23 22:39:56,196 [INFO] Use pytorch device_name: cuda:0
2026-03-23 22:39:56,196 [INFO] Load pretrained SentenceTransformer: google/embeddinggemma-300m
2026-03-23 22:39:56,337 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-23 22:39:56,461 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-23 22:39:56,587 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-23 22:39:56,709 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/README.md "HTTP/1.1 200 OK"
2026-03-23 22:39:56,831 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-23 22:39:56,957 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-03-23 22:39:57,087 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-03-23 22:39:57,213 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 22:39:57,351 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3543.43it/s]
2026-03-23 22:39:57,847 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 22:39:57,971 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-23 22:39:58,113 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-23 22:39:58,240 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-23 22:40:00,576 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-23 22:40:00,703 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/1_Pooling/config.json "HTTP/1.1 200 OK"
2026-03-23 22:40:00,831 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/config.json "HTTP/1.1 200 OK"
2026-03-23 22:40:01,021 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-23 22:40:01,149 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/config.json "HTTP/1.1 200 OK"
2026-03-23 22:40:01,293 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-23 22:40:01,417 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-23 22:40:01,503 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-23 22:40:01,504 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-23 22:40:01,730 [INFO] Loaded 5892 training pairs from C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r1.jsonl
2026-03-23 22:40:01,933 [INFO] Training samples: 5892
2026-03-23 22:40:01,934 [INFO] Building eval corpus for per-epoch evaluation …
2026-03-23 22:40:06,283 [INFO] Scene corpus built: 1262 movies, 123397 total scenes
2026-03-23 22:40:06,407 [INFO] Evaluator built — 100 queries, 1262 corpus docs, k=[5, 10, 20]
2026-03-23 22:40:06,470 [INFO] LoRA applied — trainable: 983040 / 303846144 (0.32%)
2026-03-23 22:40:10,173 [INFO] Trainer built — epochs=2, batch=8, mnrl_mini=8, amp=bf16, lr=2.0e-05, warmup=0.100, lora=True, evaluator=True, output=fede-embeddinggemma/round1

2026-03-23 22:59:34,094 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 1.0 after 737 steps:
2026-03-23 23:00:38,973 [INFO] Queries: 100
2026-03-23 23:00:38,973 [INFO] Corpus: 1262

2026-03-23 23:00:38,978 [INFO] Score-Function: cosine
2026-03-23 23:00:38,978 [INFO] Accuracy@5: 5.00%
2026-03-23 23:00:38,978 [INFO] Accuracy@10: 8.00%
2026-03-23 23:00:38,978 [INFO] Accuracy@20: 10.00%
2026-03-23 23:00:38,979 [INFO] Precision@5: 1.00%
2026-03-23 23:00:38,979 [INFO] Precision@10: 0.80%
2026-03-23 23:00:38,980 [INFO] Precision@20: 0.50%
2026-03-23 23:00:38,980 [INFO] Recall@5: 5.00%
2026-03-23 23:00:38,980 [INFO] Recall@10: 8.00%
2026-03-23 23:00:38,980 [INFO] Recall@20: 10.00%
2026-03-23 23:00:38,981 [INFO] MRR@20: 0.0295
2026-03-23 23:00:38,981 [INFO] NDCG@20: 0.0454
2026-03-23 23:00:38,981 [INFO] MAP@20: 0.0295
2026-03-23 23:00:38,985 [INFO] Saving model checkpoint to fede-embeddinggemma/round1\checkpoint-737
2026-03-23 23:00:38,986 [INFO] Save model to fede-embeddinggemma/round1\checkpoint-737
2026-03-23 23:00:39,146 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 23:00:39,269 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 23:19:59,974 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 2.0 after 1474 steps:
2026-03-23 23:21:05,263 [INFO] Queries: 100
2026-03-23 23:21:05,264 [INFO] Corpus: 1262

2026-03-23 23:21:05,267 [INFO] Score-Function: cosine
2026-03-23 23:21:05,268 [INFO] Accuracy@5: 6.00%
2026-03-23 23:21:05,268 [INFO] Accuracy@10: 9.00%
2026-03-23 23:21:05,268 [INFO] Accuracy@20: 9.00%
2026-03-23 23:21:05,269 [INFO] Precision@5: 1.20%
2026-03-23 23:21:05,269 [INFO] Precision@10: 0.90%
2026-03-23 23:21:05,269 [INFO] Precision@20: 0.45%
2026-03-23 23:21:05,270 [INFO] Recall@5: 6.00%
2026-03-23 23:21:05,270 [INFO] Recall@10: 9.00%
2026-03-23 23:21:05,270 [INFO] Recall@20: 9.00%
2026-03-23 23:21:05,271 [INFO] MRR@20: 0.0458
2026-03-23 23:21:05,271 [INFO] NDCG@20: 0.0562
2026-03-23 23:21:05,271 [INFO] MAP@20: 0.0458
2026-03-23 23:21:05,274 [INFO] Saving model checkpoint to fede-embeddinggemma/round1\checkpoint-1474
2026-03-23 23:21:05,275 [INFO] Save model to fede-embeddinggemma/round1\checkpoint-1474
2026-03-23 23:21:05,425 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 23:21:05,562 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 23:21:06,702 [INFO] Loading best model state from fede-embeddinggemma/round1\checkpoint-1474
2026-03-23 23:21:06,703 [INFO] Loading embedding model: fede-embeddinggemma/round1\checkpoint-1474
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3226.10it/s]
2026-03-23 23:21:10,114 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-23 23:21:10,136 [INFO] Save model to fede-embeddinggemma/round1
2026-03-23 23:21:10,280 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 23:21:10,408 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"

✅ Stage 3 complete: round-1 model saved to fede-embeddinggemma/round1

In [7]:
import gc

# Free training objects before loading the corpus + model for hard-negative mining.
for _var in ("model", "trainer", "train_data", "eval_corpus", "evaluator"):
    if _var in globals():
        del globals()[_var]
gc.collect()
print("🧹 Stage 3 objects released")

🧹 Stage 3 objects released

---
## Stage 4 — Mine hard negatives

Uses the round-1 model to replace random negatives with semantically close (but wrong) scenes.
This makes round-2 training significantly harder and usually gives the biggest quality jump.

⚠️ Peak RAM: loads round-1 model + full scene corpus simultaneously.
Pass `--movies N` equivalent by setting `EVAL_MOVIES` above if you OOM.

In [8]:
from finetuning.dataset.negative_miner import CorpusIndex, mine_hard_negatives

r1_model = load_model(ROUND1_MODEL_DIR)

log.info("Building scene corpus …")
corpus = build_scene_corpus(max_movies=EVAL_MOVIES)

log.info("Building embedding index …")
index = CorpusIndex.build(corpus, r1_model)

log.info("Loading round-1 dataset …")
with open(r1_path) as f:
    r1_rows = [json.loads(line) for line in f]

log.info("Mining hard negatives for %d pairs …", len(r1_rows))
r2_path.parent.mkdir(parents=True, exist_ok=True)
with open(r2_path, "w", encoding="utf-8") as out:
    for i, row in enumerate(r1_rows, 1):
        hard_negs = mine_hard_negatives(
            query=row["anchor"],
            movie_id=row["movie_id"],
            index=index,
            model=r1_model,
            n=cfg.HARD_NEGATIVES_PER_QUERY,
        )
        row["negatives"] = hard_negs
        out.write(json.dumps(row, ensure_ascii=False) + "\n")
        if i % 500 == 0:
            log.info("  %d / %d", i, len(r1_rows))

print(f"\n✅ Stage 4 complete: {len(r1_rows)} pairs with hard negatives → {r2_path}")

2026-03-23 23:21:11,654 [INFO] Loading embedding model: fede-embeddinggemma/round1
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3465.52it/s]
2026-03-23 23:21:14,912 [INFO] Use pytorch device_name: cuda:0
2026-03-23 23:21:14,990 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-23 23:21:14,991 [INFO] Building scene corpus …
2026-03-23 23:21:19,293 [INFO] Scene corpus built: 1262 movies, 123397 total scenes
2026-03-23 23:21:19,295 [INFO] Building embedding index …
2026-03-23 23:21:19,314 [INFO] Encoding 123397 scenes for hard-negative index …
Batches: 100%|██████████| 965/965 [08:17<00:00,  1.94it/s]
2026-03-23 23:29:41,111 [INFO] Loading round-1 dataset …
2026-03-23 23:29:41,341 [INFO] Mining hard negatives for 5892 pairs …
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.41it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.70it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.84it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.89it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.91it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.84it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.84it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.89it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.87it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.89it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.33it/s]

✅ Stage 4 complete: 5892 pairs with hard negatives → C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r2.jsonl

---
## Stage 5 — Train Round 2

Continues fine-tuning from the round-1 checkpoint using the hard-negative dataset.

In [9]:
r2_model   = load_model(ROUND1_MODEL_DIR)  # start from round-1 weights
train_data2 = load_training_dataset(r2_path)
log.info("Round-2 training samples: %d", len(train_data2))

evaluator2 = None
if eval_path.exists():
    eval_corpus2 = build_scene_corpus(max_movies=EVAL_MOVIES)
    evaluator2 = build_evaluator(eval_path, eval_corpus2)

trainer2 = build_trainer(
    model=r2_model,
    train_dataset=train_data2,
    output_dir=ROUND2_MODEL_DIR,
    evaluator=evaluator2,
    use_lora=USE_LORA,
    cached_mnrl_mini_batch=CACHED_MNRL_MINI_BATCH,
    **train_kwargs,
)

trainer2.train()
r2_model.save(ROUND2_MODEL_DIR)
print(f"\n✅ Stage 5 complete: round-2 model saved to {ROUND2_MODEL_DIR}")

2026-03-23 23:40:38,782 [INFO] Loading embedding model: fede-embeddinggemma/round1
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 2429.16it/s]
2026-03-23 23:40:43,649 [INFO] Use pytorch device_name: cuda:0
2026-03-23 23:40:43,752 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-23 23:40:44,125 [INFO] Loaded 5892 training pairs from C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r2.jsonl
2026-03-23 23:40:44,393 [INFO] Round-2 training samples: 5892
2026-03-23 23:40:48,607 [INFO] Scene corpus built: 1262 movies, 123397 total scenes
2026-03-23 23:40:48,670 [INFO] Evaluator built — 100 queries, 1262 corpus docs, k=[5, 10, 20]
2026-03-23 23:40:48,671 [INFO] Model already has LoRA adapters loaded; reusing existing PEFT model
2026-03-23 23:40:53,732 [INFO] Trainer built — epochs=2, batch=8, mnrl_mini=8, amp=bf16, lr=2.0e-05, warmup=0.100, lora=True, evaluator=True, output=fede-embeddinggemma/round2

2026-03-24 00:02:16,967 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 1.0 after 737 steps:
2026-03-24 00:03:21,551 [INFO] Queries: 100
2026-03-24 00:03:21,552 [INFO] Corpus: 1262

2026-03-24 00:03:21,556 [INFO] Score-Function: cosine
2026-03-24 00:03:21,557 [INFO] Accuracy@5: 1.00%
2026-03-24 00:03:21,557 [INFO] Accuracy@10: 1.00%
2026-03-24 00:03:21,557 [INFO] Accuracy@20: 1.00%
2026-03-24 00:03:21,558 [INFO] Precision@5: 0.20%
2026-03-24 00:03:21,558 [INFO] Precision@10: 0.10%
2026-03-24 00:03:21,558 [INFO] Precision@20: 0.05%
2026-03-24 00:03:21,558 [INFO] Recall@5: 1.00%
2026-03-24 00:03:21,559 [INFO] Recall@10: 1.00%
2026-03-24 00:03:21,559 [INFO] Recall@20: 1.00%
2026-03-24 00:03:21,559 [INFO] MRR@20: 0.0100
2026-03-24 00:03:21,559 [INFO] NDCG@20: 0.0100
2026-03-24 00:03:21,560 [INFO] MAP@20: 0.0100
2026-03-24 00:03:21,563 [INFO] Saving model checkpoint to fede-embeddinggemma/round2\checkpoint-737
2026-03-24 00:03:21,564 [INFO] Save model to fede-embeddinggemma/round2\checkpoint-737
2026-03-24 00:03:21,715 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-24 00:03:21,845 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-24 00:03:22,269 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-24 00:24:33,697 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 2.0 after 1474 steps:
2026-03-24 00:25:38,099 [INFO] Queries: 100
2026-03-24 00:25:38,100 [INFO] Corpus: 1262

2026-03-24 00:25:38,104 [INFO] Score-Function: cosine
2026-03-24 00:25:38,104 [INFO] Accuracy@5: 1.00%
2026-03-24 00:25:38,105 [INFO] Accuracy@10: 2.00%
2026-03-24 00:25:38,105 [INFO] Accuracy@20: 3.00%
2026-03-24 00:25:38,105 [INFO] Precision@5: 0.20%
2026-03-24 00:25:38,105 [INFO] Precision@10: 0.20%
2026-03-24 00:25:38,106 [INFO] Precision@20: 0.15%
2026-03-24 00:25:38,106 [INFO] Recall@5: 1.00%
2026-03-24 00:25:38,106 [INFO] Recall@10: 2.00%
2026-03-24 00:25:38,106 [INFO] Recall@20: 3.00%
2026-03-24 00:25:38,107 [INFO] MRR@20: 0.0036
2026-03-24 00:25:38,107 [INFO] NDCG@20: 0.0092
2026-03-24 00:25:38,107 [INFO] MAP@20: 0.0036
2026-03-24 00:25:38,110 [INFO] Saving model checkpoint to fede-embeddinggemma/round2\checkpoint-1474
2026-03-24 00:25:38,111 [INFO] Save model to fede-embeddinggemma/round2\checkpoint-1474
2026-03-24 00:25:38,277 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-24 00:25:38,407 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-24 00:25:39,357 [INFO] Loading best model state from fede-embeddinggemma/round2\checkpoint-737
2026-03-24 00:25:39,357 [INFO] Loading embedding model: fede-embeddinggemma/round2\checkpoint-737
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 2232.56it/s]
2026-03-24 00:25:42,844 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-24 00:25:42,864 [INFO] Save model to fede-embeddinggemma/round2
2026-03-24 00:25:43,004 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-24 00:25:43,136 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"

✅ Stage 5 complete: round-2 model saved to fede-embeddinggemma/round2

In [10]:
import gc

# Free the corpus index + r1_model before loading the training model for Round 2.
# The CorpusIndex holds all 117k scene embeddings in RAM — ~350 MB.
for _var in ("r1_model", "index", "corpus", "r1_rows"):
    if _var in globals():
        del globals()[_var]
gc.collect()
print("🧹 Stage 4 objects released")

🧹 Stage 4 objects released

---
## Stage 6 — Evaluate

Evaluates base, round-1, and round-2 models using **scene-level max-pool**:
each scene is embedded individually, and the movie score is the max cosine
similarity across its scenes. No Qdrant required — purely in-memory.

In [1]:
from pathlib import Path
import json
import logging

import finetuning.config as cfg
from finetuning.training.model import load_model
from finetuning.corpus.scene_corpus import build_scene_corpus
from finetuning.evaluation.scene_evaluator import run_scene_eval

log = logging.getLogger(__name__)

ROUND1_MODEL_DIR = "fede-embeddinggemma/round1"
ROUND2_MODEL_DIR = "fede-embeddinggemma/round2"
EVAL_MOVIES      = None
eval_path        = cfg.FINETUNING_DATA_DIR / "eval_queries.json"

eval_corpus = build_scene_corpus(max_movies=EVAL_MOVIES)

models_to_eval = {
    "base"   : None,              # None → loads config.EMBEDDING_MODEL_ID
    "round1" : ROUND1_MODEL_DIR,
    "round2" : ROUND2_MODEL_DIR,
}

results = {}
for name, model_path in models_to_eval.items():
    if model_path is not None and not Path(model_path).exists():
        log.warning("Skipping %s — directory not found", name)
        continue
    log.info("Evaluating %s …", name)
    m = load_model(model_path)
    metrics = run_scene_eval(m, eval_corpus, eval_path=eval_path)
    results[name] = metrics["summary"]
    del m

# Pretty-print comparison table
print(f"\n{'Model':<10} {'MRR':>6}  {'Acc@5':>6}  {'Acc@10':>7}  {'Acc@20':>7}")
print("-" * 45)
for name, s in results.items():
    print(
        f"{name:<10} {s.get('mrr', 0):>6.3f}  "
        f"{s.get('accuracy_at_5', 0):>6.3f}  "
        f"{s.get('accuracy_at_10', 0):>7.3f}  "
        f"{s.get('accuracy_at_20', 0):>7.3f}"
    )

# Save report
report_path = cfg.FINETUNING_DATA_DIR / "eval_report.json"
report_path.write_text(json.dumps(results, indent=2, ensure_ascii=False))
print(f"\n✅ Stage 6 complete — report saved to {report_path}")

c:\Users\anzez\University\ML\fede\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3819.95it/s]

  Encoding 123397 scenes from 1262 movies …

Batches: 100%|██████████| 1929/1929 [08:03<00:00,  3.99it/s]

  Embedding shape: (123397, 768), dtype: float32
  First 5 norms: [1.0016311 1.0037105 1.0010481 1.0035138 1.0010163]
  Eval queries: 184 total, 184 valid (target in corpus), 0 skipped
  Sample query: A young woman tells her boyfriend she's pregnant, and while he's initially overj…
  Target: trap_livin' | found in top-20: False
    #1 back_up_plan,_the                   score=0.4651
    #2 fast_times_at_ridgemont_high        score=0.4546
    #3 knocked_up                          score=0.4540

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3640.48it/s]

  Encoding 123397 scenes from 1262 movies …

Batches: 100%|██████████| 1929/1929 [08:20<00:00,  3.86it/s]

  Embedding shape: (123397, 768), dtype: float32
  First 5 norms: [1.0016433  0.9986336  1.003297   0.99844766 0.99821824]
  Eval queries: 184 total, 184 valid (target in corpus), 0 skipped
  Sample query: A young woman tells her boyfriend she's pregnant, and while he's initially overj…
  Target: trap_livin' | found in top-20: True
    #1 knocked_up                          score=0.6346
    #2 trainwreck                          score=0.6261
    #3 ghost_world                         score=0.6135

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3883.28it/s]

  Encoding 123397 scenes from 1262 movies …

Batches: 100%|██████████| 1929/1929 [08:16<00:00,  3.89it/s]

  Embedding shape: (123397, 768), dtype: float32
  First 5 norms: [1.0000849 1.002911  0.9981679 0.9982873 1.0036095]
  Eval queries: 184 total, 184 valid (target in corpus), 0 skipped
  Sample query: A young woman tells her boyfriend she's pregnant, and while he's initially overj…
  Target: trap_livin' | found in top-20: False
    #1 cruel_intentions                    score=1.0023
    #2 body_of_evidence                    score=1.0022
    #3 chinatown                           score=1.0022

Model         MRR   Acc@5   Acc@10   Acc@20
---------------------------------------------
base        0.421   0.511    0.592    0.668
round1      0.376   0.484    0.582    0.685
round2      0.000   0.000    0.000    0.000

✅ Stage 6 complete — report saved to C:\Users\anzez\University\ML\fede\data\finetuning\eval_report.json

---
## Stage 7 — Index corpus into Qdrant

Embeds all scenes with the final model and upserts them into Qdrant.

⚠️ Make sure Qdrant is running before executing this cell.

In [ ]:
from finetuning.training.model import encode_documents
from vector_db.indexer import SceneRecord, ScriptIndexer

final_model = load_model(ROUND2_MODEL_DIR)
corpus      = build_scene_corpus()  # full corpus, no max_movies
indexer     = ScriptIndexer()

total_scenes = sum(len(e.scenes) for e in corpus.values())
log.info("Indexing %d movies, %d scenes …", len(corpus), total_scenes)

indexed = 0
for i, (movie_id, entry) in enumerate(corpus.items(), 1):
    scene_texts = [s.text for s in entry.scenes]
    embeddings  = encode_documents(final_model, scene_texts, batch_size=64)

    records = [
        SceneRecord(
            movie_id=scene.movie_id,
            movie_title=scene.movie_title,
            scene_id=scene.scene_id,
            scene_index=scene.scene_index,
            text=scene.text,
            embedding=emb.tolist(),
            scene_title=scene.scene_title,
            character_names=scene.character_names,
        )
        for scene, emb in zip(entry.scenes, embeddings)
    ]

    indexer.index_movie_batch(scenes=records, sentences=[])
    indexed += len(records)

    if i % 100 == 0:
        log.info("  %d / %d movies indexed (%d scenes)", i, len(corpus), indexed)

print(f"\n✅ Stage 7 complete: {len(corpus)} movies, {indexed} scenes indexed")