# FEDE Embedding Fine-Tuning Pipeline

Run each stage in order. Each cell is independent — you can re-run any stage without repeating earlier ones.

| Stage | What it does |
|---|---|
| 0 | Sanity checks |
| 1a | Generate queries (LLM only, no embedding model) |
| 1b | Assemble training pairs (embedding + positive assignment) |
| 2 | Generate eval queries |
| 3 | Train Round 1 |
| 4 | Mine hard negatives |
| 5 | Train Round 2 |
| 6 | Evaluate |
| 7 | Index corpus into Qdrant |

## Configuration

Edit these before running anything.

In [1]:
# ── How many movies to use for training (rest become eval pool) ──────────────
TRAIN_MOVIES     = 1200
N_EVAL_QUERIES   = 100       # held-out eval queries to generate

# ── Output directories ───────────────────────────────────────────────────────
ROUND1_MODEL_DIR = "fede-embeddinggemma/round1"
ROUND2_MODEL_DIR = "fede-embeddinggemma/round2"

# ── Training overrides (None = use config.py defaults) ───────────────────────
EPOCHS      = None   # e.g. 1 for a quick test
BATCH_SIZE  = 4      # per-device batch; try 2 on 8–12GB if you OOM
LR          = None   # e.g. 1e-5
USE_LORA    = True   # False = full fine-tune (needs more VRAM)
CACHED_MNRL_MINI_BATCH = 8   # CachedMNRL sub-batch; lower if OOM (e.g. 4)

# ── Evaluation ───────────────────────────────────────────────────────────────
EVAL_MOVIES = None   # None = full 1338-movie corpus; set e.g. 500 to save RAM

---
## Stage 0 — Sanity checks

Verify environment, credentials, and data before committing hours of compute.

In [2]:
import logging, os, json
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("pipeline")

# ── Project root ─────────────────────────────────────────────────────────────
import finetuning.config as cfg
log.info("Project root: %s", cfg.PROJECT_ROOT)

# ── Tagged scripts ────────────────────────────────────────────────────────────
tagged_files = list(cfg.TAGGED_SCRIPTS_DIR.glob("*.txt"))
log.info("Tagged scripts found: %d", len(tagged_files))
assert len(tagged_files) > 0, f"No tagged scripts in {cfg.TAGGED_SCRIPTS_DIR}"

# ── Metadata ─────────────────────────────────────────────────────────────────
with open(cfg.METADATA_PATH) as f:
    meta = json.load(f)
log.info("Metadata entries: %d", len(meta))

# ── Gemini API key (used by Batch API for dataset generation) ─────────────────
gemini_key = os.getenv("GEMINI_API_KEY", "")
assert gemini_key, "GEMINI_API_KEY is not set in .env"
log.info("Gemini key: %s…%s", gemini_key[:8], gemini_key[-4:])

# ── HF token (for gated embedding model) ─────────────────────────────────────
hf_token = os.getenv("HF_TOKEN", "")
if hf_token:
    log.info("HF_TOKEN present")
else:
    log.warning("HF_TOKEN not set — fine unless you switched to a gated model")

# ── Existing data ─────────────────────────────────────────────────────────────
raw_path  = cfg.FINETUNING_DATA_DIR / "raw_queries.jsonl"
r1_path   = cfg.FINETUNING_DATA_DIR / "training_pairs_r1.jsonl"
r2_path   = cfg.FINETUNING_DATA_DIR / "training_pairs_r2.jsonl"
eval_path = cfg.FINETUNING_DATA_DIR / "eval_queries.json"
ckpt_path = cfg.FINETUNING_DATA_DIR / "querygen_checkpoint.json"

def _count(p): return sum(1 for _ in open(p)) if p.exists() else 0

print(f"\nCurrent data state:")
print(f"  raw_queries.jsonl       : {_count(raw_path):>6} lines")
print(f"  training_pairs_r1.jsonl : {_count(r1_path):>6} lines")
print(f"  training_pairs_r2.jsonl : {_count(r2_path):>6} lines")
print(f"  eval_queries.json       : {'exists' if eval_path.exists() else 'missing'}")
print(f"  querygen_checkpoint.json: {'exists' if ckpt_path.exists() else 'missing'}")
if ckpt_path.exists():
    ckpt = json.loads(ckpt_path.read_text())
    print(f"    → {len(ckpt.get('processed_movies', []))} movies in checkpoint, status={ckpt.get('status', 'in_progress')}")

print("\n✅ Sanity checks passed")

2026-03-22 22:15:47,336 [INFO] Project root: C:\Users\anzez\University\ML\fede
2026-03-22 22:15:47,341 [INFO] Tagged scripts found: 1338
2026-03-22 22:15:47,346 [INFO] Metadata entries: 1384
2026-03-22 22:15:47,346 [INFO] Gemini key: AIzaSyC1…QQDE
2026-03-22 22:15:47,347 [INFO] HF_TOKEN present

Current data state:
  raw_queries.jsonl       :   6946 lines
  training_pairs_r1.jsonl :   6946 lines
  training_pairs_r2.jsonl :      0 lines
  eval_queries.json       : exists
  querygen_checkpoint.json: exists
    → 1200 movies in checkpoint, status=queries_complete

✅ Sanity checks passed

---
## Stage 1a — Generate queries (LLM only)

Calls the LLM for every movie to produce Type A (synopsis) and Type B (scene summary) queries.
No embedding model is loaded during this stage — only API calls.

- Checkpoints every 50 movies. Safe to interrupt and resume.
- Output: `data/finetuning/raw_queries.jsonl`
- Uses structured output (Pydantic schemas) to guarantee valid JSON from the LLM.

In [8]:
# ── Stage 1a: Generate queries via LLM (no embedding model) ─────────────────
from finetuning.dataset.dataset_builder import DatasetBuilder

builder = DatasetBuilder(max_movies=TRAIN_MOVIES)
raw_queries_path = builder.generate_queries(resume=True)

n_queries = sum(1 for _ in open(raw_queries_path))
print(f"\n✅ Stage 1a complete: {n_queries} raw queries → {raw_queries_path}")
print("You can now safely restart the kernel before running Stage 1b.")

2026-03-22 19:50:38,416 [INFO] Scene corpus built: 1200 movies, 117100 total scenes
2026-03-22 19:50:38,421 [INFO] Checkpoint: 1165 movies
2026-03-22 19:50:38,435 [INFO] Found 15 extra movies in JSONL not in checkpoint — adding to skip set
2026-03-22 19:50:38,437 [INFO] 20 movies to process (1180 already done)
2026-03-22 19:50:38,468 [INFO] [1181/1200] Generating queries for Hannah and Her Sisters
2026-03-22 19:50:43,075 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:50:48,743 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:50:55,607 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:02,977 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:03,068 [INFO] [1182/1200] Generating queries for Man On Fire
2026-03-22 19:51:07,049 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:13,396 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:18,304 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:23,325 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:23,421 [INFO] [1183/1200] Generating queries for Gran Torino
2026-03-22 19:51:29,427 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:34,823 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:39,329 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:43,929 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:44,020 [INFO] [1184/1200] Generating queries for Top Gun
2026-03-22 19:51:47,419 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:53,047 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:51:58,210 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:03,599 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:03,689 [INFO] [1185/1200] Generating queries for It
2026-03-22 19:52:07,028 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:11,893 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:16,855 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:20,197 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:20,286 [INFO] [1186/1200] Generating queries for Panic Room
2026-03-22 19:52:24,829 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:29,200 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:31,861 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:36,982 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:37,065 [INFO] [1187/1200] Generating queries for Sphere
2026-03-22 19:52:41,795 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:47,193 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:53,171 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:58,614 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:52:58,721 [INFO] [1188/1200] Generating queries for Dumb and Dumber
2026-03-22 19:53:03,461 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:03,468 [WARNING] Failed to parse LLM JSON output: {
  "queries": [
    "Friends embarking on a journey to locate a newly discovered child.",
    "Moments highlighting the
2026-03-22 19:53:03,468 [WARNING] Only 0/4 synopsis queries for 'Dumb and Dumber' (expected 4)
2026-03-22 19:53:08,564 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:13,832 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:18,119 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:18,207 [INFO] [1189/1200] Generating queries for Scandal Final Pilot TV Script PDF
2026-03-22 19:53:22,923 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:27,830 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:33,048 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:38,063 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:38,148 [INFO] [1190/1200] Generating queries for Wild Bunch, The
2026-03-22 19:53:41,591 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:47,423 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:52,962 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:58,191 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:53:58,282 [INFO] [1191/1200] Generating queries for Entrapment
2026-03-22 19:54:01,828 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:07,968 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:13,544 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:18,598 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:18,687 [INFO] [1192/1200] Generating queries for Man Up
2026-03-22 19:54:22,350 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:27,443 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:32,797 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:38,083 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:38,170 [INFO] [1193/1200] Generating queries for Fantastic Woman, A
2026-03-22 19:54:41,912 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:47,221 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:52,946 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:58,193 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:54:58,280 [INFO] [1194/1200] Generating queries for Being Human
2026-03-22 19:55:03,094 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:08,960 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:14,649 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:19,712 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:19,802 [INFO] [1195/1200] Generating queries for Inventing the Abbotts
2026-03-22 19:55:25,174 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:25,181 [WARNING] Failed to parse LLM JSON output: {
  "queries": [
    "A young man from a humble background pursuing a serious relationship with a wealthy woman.",
2026-03-22 19:55:25,181 [WARNING] Only 0/4 synopsis queries for 'Inventing the Abbotts' (expected 4)
2026-03-22 19:55:31,162 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:35,320 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:41,414 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:41,505 [INFO] [1196/1200] Generating queries for Ghost
2026-03-22 19:55:46,362 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:46,365 [WARNING] Failed to parse LLM JSON output: {"queries": ["A spirit trying to warn a living person about impending danger.", "Scenes where a ghost attempts to protec
2026-03-22 19:55:46,365 [WARNING] Only 0/4 synopsis queries for 'Ghost' (expected 4)
2026-03-22 19:55:52,154 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:55:57,480 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:03,141 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:03,232 [INFO] [1197/1200] Generating queries for Mulholland Drive
2026-03-22 19:56:06,797 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:12,009 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:16,663 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:21,188 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:21,277 [INFO] [1198/1200] Generating queries for No One Will Save You
2026-03-22 19:56:26,373 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:27,002 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:31,857 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:35,714 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:40,455 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:40,544 [INFO] [1199/1200] Generating queries for Man Who Invented Christmas, The
2026-03-22 19:56:45,096 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:50,623 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:56:55,750 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:57:00,873 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:57:00,963 [INFO] [1200/1200] Generating queries for Smashed
2026-03-22 19:57:05,883 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:57:05,885 [WARNING] Failed to parse LLM JSON output: {
  "queries": [
    "Woman's excessive partying jeopardizes her elementary school teaching career.",
    "Character str
2026-03-22 19:57:05,886 [WARNING] Only 0/4 synopsis queries for 'Smashed' (expected 4)
2026-03-22 19:57:10,798 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:57:14,995 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:57:19,137 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 19:57:19,246 [INFO] Stage 1 complete: 6946 queries from 1200 movies → /Users/anze/NLP/fede/data/finetuning/raw_queries.jsonl

✅ Stage 1a complete: 6946 raw queries → /Users/anze/NLP/fede/data/finetuning/raw_queries.jsonl
You can now safely restart the kernel before running Stage 1b.

In [3]:
import gc

# Free QueryGenerator / LLM client before loading the embedding model.
if "builder" in dir():
    del builder
gc.collect()
print("Stage 1a objects released")

Stage 1a objects released

In [4]:
# ── Stage 1b: Assemble training pairs (embedding + positive assignment) ──────
# Reads raw_queries.jsonl, loads embedding model, finds best positive scene
# per query, samples random negatives, and writes training_pairs_r1.jsonl.
#
# No LLM API calls — purely local compute.
# Safe to interrupt and resume — already-processed movies are skipped.

from finetuning.dataset.dataset_builder import DatasetBuilder

builder = DatasetBuilder(max_movies=TRAIN_MOVIES)
r1_path = builder.assemble_pairs(resume=True)

pairs = sum(1 for _ in open(r1_path))
print(f"\n✅ Stage 1b complete: {pairs} training pairs → {r1_path}")

c:\Users\anzez\University\ML\fede\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-03-22 20:57:12,081 [INFO] Scene corpus built: 1200 movies, 117100 total scenes
2026-03-22 20:57:12,083 [INFO] Loading embedding model google/embeddinggemma-300m on cuda …
2026-03-22 20:57:12,084 [INFO] Loading embedding model: google/embeddinggemma-300m
2026-03-22 20:57:12,087 [INFO] Load pretrained SentenceTransformer: google/embeddinggemma-300m
2026-03-22 20:57:12,510 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-22 20:57:12,636 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-22 20:57:12,756 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-22 20:57:12,881 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/README.md "HTTP/1.1 200 OK"
2026-03-22 20:57:13,010 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-22 20:57:13,147 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-03-22 20:57:13,279 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-03-22 20:57:13,409 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 2514.75it/s]
2026-03-22 20:57:14,043 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 20:57:14,167 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-22 20:57:14,319 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-22 20:57:14,443 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-22 20:57:17,547 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-22 20:57:17,681 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/1_Pooling/config.json "HTTP/1.1 200 OK"
2026-03-22 20:57:17,806 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/config.json "HTTP/1.1 200 OK"
2026-03-22 20:57:17,943 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-22 20:57:18,074 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/config.json "HTTP/1.1 200 OK"
2026-03-22 20:57:18,210 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-22 20:57:18,341 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-22 20:57:18,567 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-22 20:57:18,568 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-22 20:57:18,590 [INFO] Assembling pairs: 6946 queries across 1200 movies (0 already done)
2026-03-22 20:58:18,040 [INFO]   [50/1200] 282 pairs written so far …
2026-03-22 20:59:16,454 [INFO]   [100/1200] 565 pairs written so far …
2026-03-22 21:00:20,211 [INFO]   [150/1200] 875 pairs written so far …
2026-03-22 21:01:29,379 [INFO]   [200/1200] 1183 pairs written so far …
2026-03-22 21:02:34,108 [INFO]   [250/1200] 1486 pairs written so far …
2026-03-22 21:03:25,760 [INFO]   [300/1200] 1759 pairs written so far …
2026-03-22 21:04:31,390 [INFO]   [350/1200] 2049 pairs written so far …
2026-03-22 21:05:32,633 [INFO]   [400/1200] 2344 pairs written so far …
2026-03-22 21:06:45,817 [INFO]   [450/1200] 2652 pairs written so far …
2026-03-22 21:07:38,639 [INFO]   [500/1200] 2927 pairs written so far …
2026-03-22 21:08:44,053 [INFO]   [550/1200] 3220 pairs written so far …
2026-03-22 21:09:39,672 [INFO]   [600/1200] 3502 pairs written so far …
2026-03-22 21:10:42,051 [INFO]   [650/1200] 3807 pairs written so far …
2026-03-22 21:11:40,208 [INFO]   [700/1200] 4080 pairs written so far …
2026-03-22 21:12:21,043 [INFO]   [750/1200] 4367 pairs written so far …
2026-03-22 21:13:28,320 [INFO]   [800/1200] 4675 pairs written so far …
2026-03-22 21:14:32,648 [INFO]   [850/1200] 4969 pairs written so far …
2026-03-22 21:15:28,925 [INFO]   [900/1200] 5246 pairs written so far …
2026-03-22 21:16:26,048 [INFO]   [950/1200] 5520 pairs written so far …
2026-03-22 21:17:35,171 [INFO]   [1000/1200] 5815 pairs written so far …
2026-03-22 21:18:37,325 [INFO]   [1050/1200] 6104 pairs written so far …
2026-03-22 21:19:25,392 [INFO]   [1100/1200] 6364 pairs written so far …
2026-03-22 21:20:31,767 [INFO]   [1150/1200] 6655 pairs written so far …
2026-03-22 21:21:34,954 [INFO]   [1200/1200] 6946 pairs written so far …
2026-03-22 21:21:34,955 [INFO] Stage 2 complete: 6946 training pairs → C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r1.jsonl

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\anzez\\University\\ML\\fede\\data\\finetuning\\querygen_checkpoint.tmp' -> 'C:\\Users\\anzez\\University\\ML\\fede\\data\\finetuning\\querygen_checkpoint.json'

In [5]:
import gc

# Free embedding model + corpus from Stage 1b before loading training model.
if "builder" in dir():
    del builder
gc.collect()
print("Stage 1b objects released")

Stage 1b objects released

In [ ]:
# (Optional) Clear the checkpoint to force a full re-run of Stage 1a
# import os
# ckpt = cfg.FINETUNING_DATA_DIR / "querygen_checkpoint.json"
# if ckpt.exists():
#     os.remove(ckpt)
#     print("Checkpoint cleared")

In [ ]:
# (Legacy) Run both stages in one call — use Stage 1a + 1b cells above instead.
# from finetuning.dataset.dataset_builder import DatasetBuilder
# builder = DatasetBuilder(max_movies=TRAIN_MOVIES)
# r1_path = builder.build(resume=True)
# pairs = sum(1 for _ in open(r1_path))
# print(f"\n✅ Stage 1 complete: {pairs} pairs → {r1_path}")

---
## Stage 2 — Generate eval queries

Generates ~100 held-out evaluation queries from movies **not** in the training set.

⚠️ Must run **after Stage 1** — reads the checkpoint to know which movies to exclude.

In [7]:
from finetuning.corpus.scene_corpus import load_metadata
from finetuning.dataset.query_generator import load_checkpoint
from finetuning.evaluation.dataset_generator import generate_eval_dataset

ckpt = load_checkpoint()
assert ckpt, "No checkpoint found — run Stage 1 first"
training_ids = set(ckpt.get("processed_movies", []))
log.info("Excluding %d training movies from eval pool", len(training_ids))

metadata = load_metadata()
eval_path = generate_eval_dataset(
    corpus_movie_ids=training_ids,
    metadata=metadata,
    n=N_EVAL_QUERIES,
)

with open(eval_path) as f:
    eval_queries = json.load(f)
print(f"\n✅ Stage 2 complete: {len(eval_queries)} eval queries → {eval_path}")
print("Sample:", eval_queries[0])

2026-03-22 21:25:19,391 [INFO] Excluding 1200 training movies from eval pool
2026-03-22 21:25:19,666 [INFO] Generating eval queries from 173 candidate movies (target: 100)
2026-03-22 21:25:24,962 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:27,826 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:31,396 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:36,323 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:38,631 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:42,140 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:47,436 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:49,436 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:52,052 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:56,678 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:25:59,831 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:03,971 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:06,822 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:10,341 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:13,964 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:16,571 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:19,706 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:23,460 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:27,230 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:30,849 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:33,586 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:38,023 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:40,607 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:46,041 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:48,530 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:51,483 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:53,471 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:55,844 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:26:57,850 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:01,750 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:05,732 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:08,803 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:12,020 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:15,176 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:18,518 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:21,461 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:24,366 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:28,058 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:31,234 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:36,252 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:39,609 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:44,400 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:47,472 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:50,372 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:54,573 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:27:59,578 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:01,094 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:05,413 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:08,072 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:10,219 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:13,679 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:17,084 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:20,397 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:23,893 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:25,655 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:28,950 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:31,857 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:35,179 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:38,751 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:41,949 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:46,924 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:50,668 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:53,807 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:28:57,370 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:02,541 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:04,576 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:09,454 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:14,280 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:19,414 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:24,481 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:27,997 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:31,515 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:34,381 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:36,807 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:40,047 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:43,476 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:46,617 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:49,617 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:52,169 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:55,727 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:29:58,710 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:03,361 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:08,361 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:13,473 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:16,629 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:18,606 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:22,383 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:27,667 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:30,184 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:35,175 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:37,866 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:40,223 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:45,286 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:48,224 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:51,842 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:30:57,480 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:01,465 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:04,276 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:07,441 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:08,991 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:12,138 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:14,016 [INFO] HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/openai/chat/completions "HTTP/1.1 200 OK"
2026-03-22 21:31:14,100 [INFO] Eval dataset saved: 100 queries → C:\Users\anzez\University\ML\fede\data\finetuning\eval_queries.json

✅ Stage 2 complete: 100 eval queries → C:\Users\anzez\University\ML\fede\data\finetuning\eval_queries.json
Sample: {'query': 'A district attorney leads an extensive investigation into the assassination of a national president.', 'movie_id': 'jfk', 'movie_title': 'JFK'}

In [ ]:
# (Cleanup already handled by cells above)

---
## Stage 3 — Train Round 1

Fine-tunes the base embedding model on the round-1 dataset using `CachedMultipleNegativesRankingLoss`.
Runs retrieval eval (MRR / Accuracy@k) after each epoch if `eval_queries.json` exists.

💡 **VRAM:** Use small `BATCH_SIZE` (2–4), `USE_LORA = True`, and low `CACHED_MNRL_MINI_BATCH` (4–8) on 8–12GB GPUs. Optionally set `PYTORCH_ALLOC_CONF=expandable_segments:True` before starting Jupyter.

In [3]:
from finetuning.training.model import load_model
from finetuning.training.trainer import build_evaluator, build_trainer, load_training_dataset
from finetuning.corpus.scene_corpus import build_scene_corpus

model      = load_model()  # base model from config
train_data = load_training_dataset(r1_path)
log.info("Training samples: %d", len(train_data))

evaluator = None
if eval_path.exists():
    log.info("Building eval corpus for per-epoch evaluation …")
    eval_corpus = build_scene_corpus(max_movies=EVAL_MOVIES)
    evaluator = build_evaluator(eval_path, eval_corpus)
else:
    log.warning("eval_queries.json not found — training without per-epoch eval")

train_kwargs = {}
if EPOCHS     is not None: train_kwargs["num_epochs"]    = EPOCHS
if BATCH_SIZE is not None: train_kwargs["batch_size"]    = BATCH_SIZE
if LR         is not None: train_kwargs["learning_rate"] = LR

trainer = build_trainer(
    model=model,
    train_dataset=train_data,
    output_dir=ROUND1_MODEL_DIR,
    evaluator=evaluator,
    use_lora=USE_LORA,
    cached_mnrl_mini_batch=CACHED_MNRL_MINI_BATCH,
    **train_kwargs,
)

trainer.train()
model.save(ROUND1_MODEL_DIR)
print(f"\n✅ Stage 3 complete: round-1 model saved to {ROUND1_MODEL_DIR}")

c:\Users\anzez\University\ML\fede\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-03-22 22:16:02,640 [INFO] Loading embedding model: google/embeddinggemma-300m
2026-03-22 22:16:02,644 [INFO] Use pytorch device_name: cuda:0
2026-03-22 22:16:02,645 [INFO] Load pretrained SentenceTransformer: google/embeddinggemma-300m
2026-03-22 22:16:03,260 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-22 22:16:03,399 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-22 22:16:03,521 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-22 22:16:03,647 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/README.md "HTTP/1.1 200 OK"
2026-03-22 22:16:03,782 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-22 22:16:03,904 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-03-22 22:16:04,030 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-03-22 22:16:04,155 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 22:16:04,354 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 2007.28it/s]
2026-03-22 22:16:05,016 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 22:16:05,140 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-22 22:16:05,296 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-22 22:16:05,425 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-22 22:16:08,789 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-22 22:16:08,913 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/1_Pooling/config.json "HTTP/1.1 200 OK"
2026-03-22 22:16:09,034 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/config.json "HTTP/1.1 200 OK"
2026-03-22 22:16:09,170 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-22 22:16:09,303 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/config.json "HTTP/1.1 200 OK"
2026-03-22 22:16:09,436 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-22 22:16:09,569 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-22 22:16:09,786 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-22 22:16:09,787 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-22 22:16:10,184 [INFO] Loaded 6946 training pairs from C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r1.jsonl
2026-03-22 22:16:10,558 [INFO] Training samples: 6946
2026-03-22 22:16:10,559 [INFO] Building eval corpus for per-epoch evaluation …
2026-03-22 22:16:18,787 [INFO] Scene corpus built: 1262 movies, 123397 total scenes
2026-03-22 22:16:18,883 [INFO] Evaluator built — 100 queries, 1262 corpus docs, k=[5, 10, 20]
2026-03-22 22:16:19,004 [INFO] LoRA applied — trainable: 983040 / 303846144 (0.32%)
2026-03-22 22:16:24,559 [INFO] Trainer built — epochs=2, batch=4, mnrl_mini=8, amp=bf16, lr=2.0e-05, warmup=0.100, lora=True, evaluator=True, output=fede-embeddinggemma/round1

2026-03-22 23:09:30,591 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 1.0 after 1737 steps:
2026-03-22 23:10:54,260 [INFO] Queries: 100
2026-03-22 23:10:54,260 [INFO] Corpus: 1262

2026-03-22 23:10:54,268 [INFO] Score-Function: cosine
2026-03-22 23:10:54,269 [INFO] Accuracy@5: 5.00%
2026-03-22 23:10:54,269 [INFO] Accuracy@10: 5.00%
2026-03-22 23:10:54,269 [INFO] Accuracy@20: 6.00%
2026-03-22 23:10:54,270 [INFO] Precision@5: 1.00%
2026-03-22 23:10:54,270 [INFO] Precision@10: 0.50%
2026-03-22 23:10:54,270 [INFO] Precision@20: 0.30%
2026-03-22 23:10:54,271 [INFO] Recall@5: 5.00%
2026-03-22 23:10:54,271 [INFO] Recall@10: 5.00%
2026-03-22 23:10:54,271 [INFO] Recall@20: 6.00%
2026-03-22 23:10:54,272 [INFO] MRR@20: 0.0252
2026-03-22 23:10:54,272 [INFO] NDCG@20: 0.0333
2026-03-22 23:10:54,272 [INFO] MAP@20: 0.0252
2026-03-22 23:10:54,276 [INFO] Saving model checkpoint to fede-embeddinggemma/round1\checkpoint-1737
2026-03-22 23:10:54,277 [INFO] Save model to fede-embeddinggemma/round1\checkpoint-1737
2026-03-22 23:10:54,457 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 23:10:54,588 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 23:57:36,314 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 2.0 after 3474 steps:
2026-03-22 23:58:46,525 [INFO] Queries: 100
2026-03-22 23:58:46,526 [INFO] Corpus: 1262

2026-03-22 23:58:46,530 [INFO] Score-Function: cosine
2026-03-22 23:58:46,530 [INFO] Accuracy@5: 3.00%
2026-03-22 23:58:46,531 [INFO] Accuracy@10: 6.00%
2026-03-22 23:58:46,531 [INFO] Accuracy@20: 9.00%
2026-03-22 23:58:46,531 [INFO] Precision@5: 0.60%
2026-03-22 23:58:46,531 [INFO] Precision@10: 0.60%
2026-03-22 23:58:46,532 [INFO] Precision@20: 0.45%
2026-03-22 23:58:46,532 [INFO] Recall@5: 3.00%
2026-03-22 23:58:46,532 [INFO] Recall@10: 6.00%
2026-03-22 23:58:46,532 [INFO] Recall@20: 9.00%
2026-03-22 23:58:46,533 [INFO] MRR@20: 0.0159
2026-03-22 23:58:46,533 [INFO] NDCG@20: 0.0318
2026-03-22 23:58:46,533 [INFO] MAP@20: 0.0159
2026-03-22 23:58:46,536 [INFO] Saving model checkpoint to fede-embeddinggemma/round1\checkpoint-3474
2026-03-22 23:58:46,537 [INFO] Save model to fede-embeddinggemma/round1\checkpoint-3474
2026-03-22 23:58:46,692 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 23:58:46,812 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 23:58:48,080 [INFO] Loading best model from fede-embeddinggemma/round1\checkpoint-1737 (score: 0.02516666666666667).
2026-03-22 23:58:48,103 [INFO] Use pytorch device_name: cuda:0
2026-03-22 23:58:48,104 [INFO] Load pretrained SentenceTransformer: fede-embeddinggemma/round1\checkpoint-1737
2026-03-22 23:58:48,268 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-22 23:58:48,395 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 9650.56it/s]
Loading weights: 0it [00:00, ?it/s]
Gemma3TextModel LOAD REPORT from: fede-embeddinggemma/round1\checkpoint-1737
Key                                                                     | Status     |
------------------------------------------------------------------------+------------+-
base_model.model.layers.{0...23}.self_attn.v_proj.lora_A.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.v_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_A.default.weight | UNEXPECTED |
layers.{0...23}.self_attn.q_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.q_proj.lora_B.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_B.default.weight                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
2026-03-22 23:58:52,115 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-22 23:58:52,121 [ERROR] Could not load the best model from fede-embeddinggemma/round1\checkpoint-1737. Error: Error(s) in loading state_dict for SentenceTransformer:

✅ Stage 3 complete: round-1 model saved to fede-embeddinggemma/round1

In [5]:
import gc

# Free training objects before loading the corpus + model for hard-negative mining.
for _var in ("model", "trainer", "train_data", "eval_corpus", "evaluator"):
    if _var in globals():
        del globals()[_var]
gc.collect()
print("🧹 Stage 3 objects released")

🧹 Stage 3 objects released

---
## Stage 4 — Mine hard negatives

Uses the round-1 model to replace random negatives with semantically close (but wrong) scenes.
This makes round-2 training significantly harder and usually gives the biggest quality jump.

⚠️ Peak RAM: loads round-1 model + full scene corpus simultaneously.
Pass `--movies N` equivalent by setting `EVAL_MOVIES` above if you OOM.

In [6]:
from finetuning.dataset.negative_miner import CorpusIndex, mine_hard_negatives

r1_model = load_model(ROUND1_MODEL_DIR)

log.info("Building scene corpus …")
corpus = build_scene_corpus(max_movies=EVAL_MOVIES)

log.info("Building embedding index …")
index = CorpusIndex.build(corpus, r1_model)

log.info("Loading round-1 dataset …")
with open(r1_path) as f:
    r1_rows = [json.loads(line) for line in f]

log.info("Mining hard negatives for %d pairs …", len(r1_rows))
r2_path.parent.mkdir(parents=True, exist_ok=True)
with open(r2_path, "w", encoding="utf-8") as out:
    for i, row in enumerate(r1_rows, 1):
        hard_negs = mine_hard_negatives(
            query=row["anchor"],
            movie_id=row["movie_id"],
            index=index,
            model=r1_model,
            n=cfg.HARD_NEGATIVES_PER_QUERY,
        )
        row["negatives"] = hard_negs
        out.write(json.dumps(row, ensure_ascii=False) + "\n")
        if i % 500 == 0:
            log.info("  %d / %d", i, len(r1_rows))

print(f"\n✅ Stage 4 complete: {len(r1_rows)} pairs with hard negatives → {r2_path}")

2026-03-23 00:00:42,805 [INFO] Loading embedding model: fede-embeddinggemma/round1
2026-03-23 00:00:42,808 [INFO] Use pytorch device_name: cuda:0
2026-03-23 00:00:42,809 [INFO] Load pretrained SentenceTransformer: fede-embeddinggemma/round1
2026-03-23 00:00:42,960 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 00:00:43,084 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 4328.43it/s]
Loading weights: 0it [00:00, ?it/s]
Gemma3TextModel LOAD REPORT from: fede-embeddinggemma/round1
Key                                                                     | Status     |
------------------------------------------------------------------------+------------+-
base_model.model.layers.{0...23}.self_attn.v_proj.lora_A.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.v_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_A.default.weight | UNEXPECTED |
layers.{0...23}.self_attn.q_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.q_proj.lora_B.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_B.default.weight                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
2026-03-23 00:00:46,559 [INFO] HTTP Request: GET https://huggingface.co/api/models/fede-embeddinggemma/round1 "HTTP/1.1 404 Not Found"
2026-03-23 00:00:46,638 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-23 00:00:46,639 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-23 00:00:46,639 [INFO] Building scene corpus …
2026-03-23 00:00:59,952 [INFO] Scene corpus built: 1262 movies, 123397 total scenes
2026-03-23 00:00:59,953 [INFO] Building embedding index …
2026-03-23 00:00:59,972 [INFO] Encoding 123397 scenes for hard-negative index …
Batches: 100%|██████████| 965/965 [08:22<00:00,  1.92it/s]
2026-03-23 00:09:27,090 [INFO] Loading round-1 dataset …
2026-03-23 00:09:27,382 [INFO] Mining hard negatives for 6946 pairs …
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.96it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.74it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.41it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.86it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.76it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.87it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.83it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.12it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.91it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.12it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.86it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.41it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.84it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.71it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.80it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.91it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.64it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.91it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.86it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.96it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.96it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.96it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.64it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]

✅ Stage 4 complete: 6946 pairs with hard negatives → C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r2.jsonl

---
## Stage 5 — Train Round 2

Continues fine-tuning from the round-1 checkpoint using the hard-negative dataset.

In [7]:
r2_model   = load_model(ROUND1_MODEL_DIR)  # start from round-1 weights
train_data2 = load_training_dataset(r2_path)
log.info("Round-2 training samples: %d", len(train_data2))

evaluator2 = None
if eval_path.exists():
    eval_corpus2 = build_scene_corpus(max_movies=EVAL_MOVIES)
    evaluator2 = build_evaluator(eval_path, eval_corpus2)

trainer2 = build_trainer(
    model=r2_model,
    train_dataset=train_data2,
    output_dir=ROUND2_MODEL_DIR,
    evaluator=evaluator2,
    use_lora=USE_LORA,
    cached_mnrl_mini_batch=CACHED_MNRL_MINI_BATCH,
    **train_kwargs,
)

trainer2.train()
r2_model.save(ROUND2_MODEL_DIR)
print(f"\n✅ Stage 5 complete: round-2 model saved to {ROUND2_MODEL_DIR}")

2026-03-23 00:24:03,778 [INFO] Loading embedding model: fede-embeddinggemma/round1
2026-03-23 00:24:03,781 [INFO] Use pytorch device_name: cuda:0
2026-03-23 00:24:03,781 [INFO] Load pretrained SentenceTransformer: fede-embeddinggemma/round1
2026-03-23 00:24:03,912 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 00:24:04,034 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 2743.93it/s]
Loading weights: 0it [00:00, ?it/s]
Gemma3TextModel LOAD REPORT from: fede-embeddinggemma/round1
Key                                                                     | Status     |
------------------------------------------------------------------------+------------+-
base_model.model.layers.{0...23}.self_attn.v_proj.lora_A.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.v_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_A.default.weight | UNEXPECTED |
layers.{0...23}.self_attn.q_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.q_proj.lora_B.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_B.default.weight                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
2026-03-23 00:24:07,565 [INFO] HTTP Request: GET https://huggingface.co/api/models/fede-embeddinggemma/round1 "HTTP/1.1 404 Not Found"
2026-03-23 00:24:07,651 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-23 00:24:07,652 [INFO] Model loaded — device=cuda:0, dim=768
2026-03-23 00:24:07,968 [INFO] Loaded 6946 training pairs from C:\Users\anzez\University\ML\fede\data\finetuning\training_pairs_r2.jsonl
2026-03-23 00:24:08,427 [INFO] Round-2 training samples: 6946
2026-03-23 00:24:12,886 [INFO] Scene corpus built: 1262 movies, 123397 total scenes
2026-03-23 00:24:12,958 [INFO] Evaluator built — 100 queries, 1262 corpus docs, k=[5, 10, 20]
c:\Users\anzez\University\ML\fede\.venv\Lib\site-packages\peft\mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
c:\Users\anzez\University\ML\fede\.venv\Lib\site-packages\peft\tuners\tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
2026-03-23 00:24:13,023 [INFO] LoRA applied — trainable: 983040 / 303846144 (0.32%)
2026-03-23 00:24:17,940 [INFO] Trainer built — epochs=2, batch=4, mnrl_mini=8, amp=bf16, lr=2.0e-05, warmup=0.100, lora=True, evaluator=True, output=fede-embeddinggemma/round2

2026-03-23 01:14:10,648 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 1.0 after 1737 steps:
2026-03-23 01:15:20,840 [INFO] Queries: 100
2026-03-23 01:15:20,840 [INFO] Corpus: 1262

2026-03-23 01:15:20,844 [INFO] Score-Function: cosine
2026-03-23 01:15:20,845 [INFO] Accuracy@5: 0.00%
2026-03-23 01:15:20,845 [INFO] Accuracy@10: 0.00%
2026-03-23 01:15:20,845 [INFO] Accuracy@20: 1.00%
2026-03-23 01:15:20,845 [INFO] Precision@5: 0.00%
2026-03-23 01:15:20,846 [INFO] Precision@10: 0.00%
2026-03-23 01:15:20,846 [INFO] Precision@20: 0.05%
2026-03-23 01:15:20,846 [INFO] Recall@5: 0.00%
2026-03-23 01:15:20,846 [INFO] Recall@10: 0.00%
2026-03-23 01:15:20,847 [INFO] Recall@20: 1.00%
2026-03-23 01:15:20,847 [INFO] MRR@20: 0.0005
2026-03-23 01:15:20,847 [INFO] NDCG@20: 0.0023
2026-03-23 01:15:20,847 [INFO] MAP@20: 0.0005
2026-03-23 01:15:20,850 [INFO] Saving model checkpoint to fede-embeddinggemma/round2\checkpoint-1737
2026-03-23 01:15:20,851 [INFO] Save model to fede-embeddinggemma/round2\checkpoint-1737
2026-03-23 01:15:20,991 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 01:15:21,112 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 01:15:21,599 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-23 02:05:44,966 [INFO] Information Retrieval Evaluation of the model on the fede-ir-eval dataset in epoch 2.0 after 3474 steps:
2026-03-23 02:06:55,083 [INFO] Queries: 100
2026-03-23 02:06:55,084 [INFO] Corpus: 1262

2026-03-23 02:06:55,088 [INFO] Score-Function: cosine
2026-03-23 02:06:55,088 [INFO] Accuracy@5: 0.00%
2026-03-23 02:06:55,088 [INFO] Accuracy@10: 0.00%
2026-03-23 02:06:55,089 [INFO] Accuracy@20: 0.00%
2026-03-23 02:06:55,089 [INFO] Precision@5: 0.00%
2026-03-23 02:06:55,089 [INFO] Precision@10: 0.00%
2026-03-23 02:06:55,090 [INFO] Precision@20: 0.00%
2026-03-23 02:06:55,090 [INFO] Recall@5: 0.00%
2026-03-23 02:06:55,090 [INFO] Recall@10: 0.00%
2026-03-23 02:06:55,090 [INFO] Recall@20: 0.00%
2026-03-23 02:06:55,091 [INFO] MRR@20: 0.0000
2026-03-23 02:06:55,091 [INFO] NDCG@20: 0.0000
2026-03-23 02:06:55,091 [INFO] MAP@20: 0.0000
2026-03-23 02:06:55,094 [INFO] Saving model checkpoint to fede-embeddinggemma/round2\checkpoint-3474
2026-03-23 02:06:55,095 [INFO] Save model to fede-embeddinggemma/round2\checkpoint-3474
2026-03-23 02:06:55,257 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 02:06:55,380 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 02:06:56,586 [INFO] Loading best model from fede-embeddinggemma/round2\checkpoint-1737 (score: 0.0005263157894736842).
2026-03-23 02:06:56,590 [INFO] Use pytorch device_name: cuda:0
2026-03-23 02:06:56,590 [INFO] Load pretrained SentenceTransformer: fede-embeddinggemma/round2\checkpoint-1737
2026-03-23 02:06:56,711 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 02:06:56,844 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 11316.38it/s]
Loading weights: 0it [00:00, ?it/s]
Gemma3TextModel LOAD REPORT from: fede-embeddinggemma/round2\checkpoint-1737
Key                                                                     | Status     |
------------------------------------------------------------------------+------------+-
base_model.model.layers.{0...23}.self_attn.v_proj.lora_A.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.v_proj.lora_B.default.weight | UNEXPECTED |
base_model.model.layers.{0...23}.self_attn.q_proj.lora_A.default.weight | UNEXPECTED |
layers.{0...23}.self_attn.q_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.q_proj.lora_B.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_A.default.weight                  | MISSING    |
layers.{0...23}.self_attn.v_proj.lora_B.default.weight                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
2026-03-23 02:07:00,864 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-23 02:07:00,870 [ERROR] Could not load the best model from fede-embeddinggemma/round2\checkpoint-1737. Error: Error(s) in loading state_dict for SentenceTransformer:

✅ Stage 5 complete: round-2 model saved to fede-embeddinggemma/round2

In [8]:
import gc

# Free the corpus index + r1_model before loading the training model for Round 2.
# The CorpusIndex holds all 117k scene embeddings in RAM — ~350 MB.
for _var in ("r1_model", "index", "corpus", "r1_rows"):
    if _var in globals():
        del globals()[_var]
gc.collect()
print("🧹 Stage 4 objects released")

🧹 Stage 4 objects released

---
## Stage 6 — Evaluate

Runs the held-out eval queries against the full scene corpus and prints MRR / Accuracy@k.

In [9]:
from finetuning.evaluation.pipeline import run_pipeline
from finetuning.evaluation.semantic_retriever import SemanticRetriever

# Evaluate base model for comparison
models_to_eval = {
    "base"   : None,              # None → loads config.EMBEDDING_MODEL_ID
    "round1" : ROUND1_MODEL_DIR,
    "round2" : ROUND2_MODEL_DIR,
}

results = {}
for name, model_path in models_to_eval.items():
    if model_path is not None and not Path(model_path).exists():
        log.warning("Skipping %s — directory not found", name)
        continue
    log.info("Evaluating %s …", name)
    m = load_model(model_path)
    retriever = SemanticRetriever(m)
    metrics = run_pipeline(retriever, eval_path=eval_path)
    results[name] = metrics["summary"]

# Pretty-print comparison table
print(f"\n{'Model':<10} {'MRR':>6}  {'Acc@5':>6}  {'Acc@10':>7}  {'Acc@20':>7}")
print("-" * 45)
for name, s in results.items():
    print(
        f"{name:<10} {s.get('mrr', 0):>6.3f}  "
        f"{s.get('accuracy_at_5', 0):>6.3f}  "
        f"{s.get('accuracy_at_10', 0):>7.3f}  "
        f"{s.get('accuracy_at_20', 0):>7.3f}"
    )

# Save report
report_path = cfg.FINETUNING_DATA_DIR / "eval_report.json"
report_path.write_text(json.dumps(results, indent=2, ensure_ascii=False))
print(f"\n✅ Stage 6 complete — report saved to {report_path}")

2026-03-23 02:07:02,562 [INFO] Evaluating base …
2026-03-23 02:07:02,563 [INFO] Loading embedding model: google/embeddinggemma-300m
2026-03-23 02:07:02,567 [INFO] Use pytorch device_name: cuda:0
2026-03-23 02:07:02,568 [INFO] Load pretrained SentenceTransformer: google/embeddinggemma-300m
2026-03-23 02:07:02,691 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-23 02:07:02,812 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-23 02:07:02,944 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-03-23 02:07:03,058 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/README.md "HTTP/1.1 200 OK"
2026-03-23 02:07:03,200 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/modules.json "HTTP/1.1 200 OK"
2026-03-23 02:07:03,324 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-03-23 02:07:03,460 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-03-23 02:07:03,584 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 02:07:03,708 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 314/314 [00:00<00:00, 3229.76it/s]
2026-03-23 02:07:04,204 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/config.json "HTTP/1.1 200 OK"
2026-03-23 02:07:04,331 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-23 02:07:04,482 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-23 02:07:04,606 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-23 02:07:07,392 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-23 02:07:07,513 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/1_Pooling/config.json "HTTP/1.1 200 OK"
2026-03-23 02:07:07,640 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/config.json "HTTP/1.1 200 OK"
2026-03-23 02:07:07,782 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/2_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-23 02:07:07,921 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/config.json "HTTP/1.1 200 OK"
2026-03-23 02:07:08,063 [INFO] HTTP Request: HEAD https://huggingface.co/google/embeddinggemma-300m/resolve/main/3_Dense/model.safetensors "HTTP/1.1 302 Found"
2026-03-23 02:07:08,207 [INFO] HTTP Request: GET https://huggingface.co/api/models/google/embeddinggemma-300m "HTTP/1.1 200 OK"
2026-03-23 02:07:08,283 [INFO] 14 prompts are loaded, with the keys: ['query', 'document', 'BitextMining', 'Clustering', 'Classification', 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification', 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization']
2026-03-23 02:07:08,284 [INFO] Model loaded — device=cuda:0, dim=768
c:\Users\anzez\University\ML\fede\.venv\Lib\site-packages\qdrant_client\qdrant_remote.py:288: UserWarning: Failed to obtain server version. Unable to check client-server compatibility. Set check_compatibility=False to skip version check.
  show_warning(

ConnectionError: Failed to connect to Qdrant in server mode: Qdrant connection validation failed: [WinError 10061] No connection could be made because the target machine actively refused it

---
## Stage 7 — Index corpus into Qdrant

Embeds all scenes with the final model and upserts them into Qdrant.

⚠️ Make sure Qdrant is running before executing this cell.

In [ ]:
from finetuning.training.model import encode_documents
from vector_db.indexer import SceneRecord, ScriptIndexer

final_model = load_model(ROUND2_MODEL_DIR)
corpus      = build_scene_corpus()  # full corpus, no max_movies
indexer     = ScriptIndexer()

total_scenes = sum(len(e.scenes) for e in corpus.values())
log.info("Indexing %d movies, %d scenes …", len(corpus), total_scenes)

indexed = 0
for i, (movie_id, entry) in enumerate(corpus.items(), 1):
    scene_texts = [s.text for s in entry.scenes]
    embeddings  = encode_documents(final_model, scene_texts, batch_size=64)

    records = [
        SceneRecord(
            movie_id=scene.movie_id,
            movie_title=scene.movie_title,
            scene_id=scene.scene_id,
            scene_index=scene.scene_index,
            text=scene.text,
            embedding=emb.tolist(),
            scene_title=scene.scene_title,
            character_names=scene.character_names,
        )
        for scene, emb in zip(entry.scenes, embeddings)
    ]

    indexer.index_movie_batch(scenes=records, sentences=[])
    indexed += len(records)

    if i % 100 == 0:
        log.info("  %d / %d movies indexed (%d scenes)", i, len(corpus), indexed)

print(f"\n✅ Stage 7 complete: {len(corpus)} movies, {indexed} scenes indexed")